domains:
  STEM:
    subjects:
      - name: Physics
        grade_min: 12
        grade_max: 13
      - name: Chemistry
        grade_min: 12
        grade_max: 13
      - name: Biology
        grade_min: 12
        grade_max: 13
      - name: Science
        grade_min: 6
        grade_max: 11

  Humanities:
    subjects:
      - name: History
        grade_min: 6
        grade_max: 13
      - name: Drama and Theatre
        grade_min: 6
        grade_max: 13
      - name: Dancing
        grade_min: 6
        grade_max: 13
      - name: Eastern Music
        grade_min: 6
        grade_max: 13
      - name: Buddhism
        grade_min: 6
        grade_max: 13
      - name: Catholicism
        grade_min: 6
        grade_max: 13
      - name: Christianity
        grade_min: 6
        grade_max: 13
      - name: Islam
        grade_min: 6
        grade_max: 13
      - name: Buddhist Civilization
        grade_min: 6
        grade_max: 13
      - name: Arts
        grade_min: 6
        grade_max: 13
      - name: Oriental Music
        grade_min: 12
        grade_max: 13
      - name: History of Sri Lanka
        grade_min: 12
        grade_max: 13
      - name: Dancing Indigenous
        grade_min: 12
        grade_max: 13

  Social Science:
    subjects:
      - name: Geography
        grade_min: 6
        grade_max: 13
      - name: Political Science
        grade_min: 12
        grade_max: 13
      - name: Citizenship Education
        grade_min: 6
        grade_max: 11
      - name: Health and Physical Science
        grade_min: 6
        grade_max: 11

  Language:
    subjects:
      - name: Sinhala Language and Literature
        grade_min: 6
        grade_max: 11
      - name: Sinhala
        grade_min: 12
        grade_max: 13

  Business Studies:
    subjects:
      - name: Business and Accounting Studies
        grade_min: 10
        grade_max: 11
      - name: Economics
        grade_min: 12
        grade_max: 13
      - name: Business Studies
        grade_min: 12
        grade_max: 13
      - name: Entrepreneurship Studies
        grade_min: 10
        grade_max: 11

  Other:
    subjects:
      - name: Home Economics
        grade_min: 10
        grade_max: 11
      - name: Agriculture and Food Technology
        grade_min: 10
        grade_max: 11
      - name: Communication and Media Studies
        grade_min: 10
        grade_max: 13
      - name: Design and Construction Technology
        grade_min: 10
        grade_max: 11
      - name: Biosystems Technology
        grade_min: 12
        grade_max: 13

education_levels:
  Junior Secondary:
    grade_min: 6
    grade_max: 9
  O-Level:
    grade_min: 10
    grade_max: 11
  A-Level:
    grade_min: 12
    grade_max: 13
